FROM python:3.11-bookworm

RUN apt-get update && apt-get install -y --no-install-recommends \
  git \
  gh \
  texlive-latex-extra \
  texlive-fonts-recommended \
  texlive-fonts-extra \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /work
